### ISSUE TITLE
iTunes Connect version validation

### ISSUE THREAD

**Issue by batesyuk** [fastlane/deliver#478]
Hi,

I recently uploaded an app for review in iTunes say (1.0). While this app was "waiting for review" I setup deliver for CI.
While testing the connection for deliver, a build was pushed to IC with the version 1.1 and successful response returned.
The result of this was that the meta data of the waiting for release app seems to have changed but the binary has stayed the same. I now have a version 1.1 app pending developer release of a version 1.0 binary.

iTunes connect side the binary seems to have been discarded (although I can not be sure) but the metadata version number has been changed to the deliver version. I skipped updating the keywords, categories and other locked metadata once a review is requested but I think it can be assumed they would have changed as well?

Steps:
Upload an app to iTunes connect and submit for app-store review
Use deliver to push a version of the application with increased version number.

Expected:
An error to be thrown like: "Cant upload a new version while there is a version waiting for review."

Observe:
The build number of application waiting for review will increase
The binary of the application waiting for review will appear to stay the same

**Comment by shyamvala** [comment]
I wonder if there is any resolution on this. I had a very similar thing happened to me twice in last two weeks.

**Comment by shyamvala** [comment]
I went back and looked at the logs and I noticed that the metadata of the app is getting updated that is waiting for review. Is this an expected behavior or is their another setting that needs to be supplied to avoid this ? This issue creates a mismatch in the app store version and the version set on the application.

**Comment by jaleksynas** [comment]
This just happened to my app as well. It also affects pilot since the interesting code is in SpaceShip::Application.

The version check/update occurs on line https://github.com/fastlane/spaceship/blob/master/lib/spaceship/tunes/application.rb#L160

It seems that it would be nice if Apple blocked this change -- making 'version' immutable in everything but 'prepare' state.

Perhaps this check is possible to check the 'status' of that version and raise an error or simply do not update the version number (or meta-data?).  Unfortunately there may be a reasonable use case where you would STILL want to update the other editable bits (like screenshots or release notes) during this sensitive time.

A major challenge here is that there seems to be ONLY ONE in flight version allowed in iTunes connect.  Leaving us in dead automation waters between "Submit for Review" and Rejected/Ready for sale.  

I'd be happy to take a crack at fixing this, but not sure how best to proceed. Any thoughts @KrauseFx? I think the version should only be updated during the prepare state (allowing all other updates and allowing the upload -- for possible future use after devReject).

**Comment by jaleksynas** [comment]
https://github.com/fastlane/spaceship/compare/master...jaleksynas:status_version_fix
Simply don't update the version! but act like you did.  The messaging in Deliver would need to be updated to be more accurate as this is no longer a boolean result. The binary gets uploaded and other steps continue as normal.

*** or ...

https://github.com/fastlane/spaceship/compare/master...jaleksynas:status_version_fix2

This allows the messaging to be clearer and not require an update to deliver in order to handle this technicality.  However, the binary would not get uploaded as this becomes considered a failure scenario.
