### ISSUE TITLE
Don't look for Info.plist in subfolders

### ISSUE THREAD

**Issue by siuying** [fastlane/deliver#73]
I'm using deliver from fastlane. When I try to publish a beta app, I got following error:

```
FATAL [2015-01-19 18:12:49.36]: App Identifier of IPA does not match with the given one ('my.company.myapp' != 'my.company.${PRODUCT_NAME:rfc1034identifier}')
```

There is no "my.company.${PRODUCT_NAME:rfc1034identifier}" in anywhere in the project.

**Comment by KrauseFx** [comment]
Take a look at your project file, it will contain exactly the string you posted, only Xcode replaces it when displaying.

What I'm worried about: why does `deliver` get this as the bundle identifier? It's probably still in the IPA file. Can you extract your `ipa` and take a look at the `plist` file ?

**Comment by siuying** [comment]
Okay you're right, in the ``Pods`` sub-folders, one of the Pods contains a ``Info.plist`` which contains that string. Its not part of the project. If I remove that file from Pods before I type ``fastlane run beta``,  I can run the command without problem. 

Inside IPA, the Info.plist is 'my.company.myapp'

**Comment by KrauseFx** [comment]
Oh, we've had this problem before. I haven't found a good solution to detect the correct `Info.plist` file inside the `.app` folder.

Which open source library is causing the problem?

I guess, having `deliver` only look one level deep to look for the `Info.plist` we should be fine.

**Comment by siuying** [comment]
The library is ``CSSSelectorConverter``. When compiled, the IPA app folder contains ``CSSSelectorConverter-Info.plist`` in the root folder. The correct file should be ``Info.plist``, so ``deliver`` found and use ``CSSSelectorConverter-Info.plist`` instead of ``Info.plist``?

**Comment by KrauseFx** [comment]
That's right, I'll fix this by only going one level deep to look for the `*.plist` file.

Yes, here it is: https://github.com/siuying/CSSSelectorConverter/blob/master/CSSSelectorConverter/CSSSelectorConverter-Info.plist

There shouldn't be a `*Info.plist` in the pod.

Still, I'll improve that behaviour of `deliver`.

As I see, it's your library, so you can fix it easily :+1:

**Comment by siuying** [comment]
Thanks! Yes it should not include that plist file (there is another plist file where it should bundle), will fix it. :+1:

**Comment by Novan123** [comment]
Hi,
we have many *.plist files in our root directory and deliver uses the wrong one and display the error. Why we have many *.plist? Because we have four targets and foreach target a unit-test-target. 

How could deliver determine the correct one?
I suggest deliver should first look for a *.plist file which is identical named like the Ripa file.

test.ipa -> test.plist
product name with spaces ipa -> product name with spaces.plist

**Comment by KrauseFx** [comment]
I just pushed [deliver 1.0.0](https://github.com/KrauseFx/deliver/releases/tag/1.0.0) and [fastlane 1.30.0](https://github.com/KrauseFx/fastlane/releases/tag/1.30.0). Please update using `sudo gem update fastlane` and let me know if everything works for you.

Also, make sure to follow the new [Migration Guide to 1.0](https://github.com/KrauseFx/deliver/blob/master/MigrationGuide.md).

I'll close this issue for now due to inactivity. Feel free to submit a new one if you're experiencing the same or another issue.
